import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean, DateTime, ForeignKey,
    Integer, String, Text
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin


class ClientReportConfig(Base, UUIDMixin, TimestampMixin):
    """
    Per-client reporting configuration set by the owner.
    Controls schedule, which ad platforms to pull, and KPI targets.

    schedule: weekly | monthly
    platforms: comma-separated e.g. "ga4,meta,google_ads"
    """

    __tablename__ = "client_report_configs"

    agency_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agencies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    client_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clients.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,   # one config per client
        index=True,
    )

    # weekly | monthly
    schedule: Mapped[str] = mapped_column(String(20), default="monthly")

    # Comma-separated platform keys: ga4,meta,google_ads
    platforms: Mapped[str] = mapped_column(String(100), default="ga4,meta,google_ads")

    # Platform-specific IDs — needed to pull data
    ga4_property_id: Mapped[str | None] = mapped_column(String(100))
    meta_ad_account_id: Mapped[str | None] = mapped_column(String(100))
    google_ads_customer_id: Mapped[str | None] = mapped_column(String(100))

    # KPI targets (JSON string) — used by Claude to assess performance
    # e.g. '{"roas": 3.0, "ctr": 2.5, "cpc": 15.0}'
    kpi_targets_json: Mapped[str | None] = mapped_column(Text)

    # Last report sent — used by scheduler to determine if report is due
    last_report_sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    def __repr__(self) -> str:
        return (
            f"<ClientReportConfig client={self.client_id} "
            f"schedule={self.schedule} platforms={self.platforms}>"
        )


class Report(Base, UUIDMixin, TimestampMixin):
    """
    A single report for a client covering a specific date range.
    Generated by the ReportingAgent LangGraph.

    status: generating → generated → delivered | failed
    """

    __tablename__ = "reports"

    agency_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agencies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    client_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Period covered by this report
    period_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    period_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # generating | generated | delivered | failed
    status: Mapped[str] = mapped_column(String(20), default="generating")

    # Raw metrics JSON — stored for auditing and re-generation
    # e.g. {"meta": {"spend": 45000, "roas": 2.8, ...}, "ga4": {...}}
    raw_metrics_json: Mapped[str | None] = mapped_column(Text)

    # Claude-generated narrative
    narrative: Mapped[str | None] = mapped_column(Text)

    # PDF file path relative to media root
    pdf_path: Mapped[str | None] = mapped_column(String(500))

    # Delivery tracking
    delivered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    delivered_via: Mapped[str | None] = mapped_column(String(50))  # email | whatsapp | both

    # Follow-up state
    client_replied: Mapped[bool] = mapped_column(Boolean, default=False)
    follow_up_sent: Mapped[bool] = mapped_column(Boolean, default=False)

    error_message: Mapped[str | None] = mapped_column(Text)

    def __repr__(self) -> str:
        return (
            f"<Report client={self.client_id} "
            f"{self.period_start.date()} → {self.period_end.date()} "
            f"status={self.status}>"
        )