"""m9 abm accounts touches notes

Revision ID: 36454ded30ce
Revises: 13140c12a31d
Create Date: 2026-04-10 15:29:47.741787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36454ded30ce'
down_revision: Union[str, None] = '13140c12a31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abm_accounts',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_linkedin', sa.String(length=500), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('intelligence_summary', sa.Text(), nullable=True),
    sa.Column('ai_next_action', sa.Text(), nullable=True),
    sa.Column('last_touch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abm_accounts_agency_id'), 'abm_accounts', ['agency_id'], unique=False)
    op.create_index(op.f('ix_abm_accounts_stage'), 'abm_accounts', ['stage'], unique=False)
    op.create_table('abm_account_notes',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('written_by', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['abm_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['written_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abm_account_notes_account_id'), 'abm_account_notes', ['account_id'], unique=False)
    op.create_table('abm_touches',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('touch_type', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('touched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['abm_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abm_touches_account_id'), 'abm_touches', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abm_touches_account_id'), table_name='abm_touches')
    op.drop_table('abm_touches')
    op.drop_index(op.f('ix_abm_account_notes_account_id'), table_name='abm_account_notes')
    op.drop_table('abm_account_notes')
    op.drop_index(op.f('ix_abm_accounts_stage'), table_name='abm_accounts')
    op.drop_index(op.f('ix_abm_accounts_agency_id'), table_name='abm_accounts')
    op.drop_table('abm_accounts')
    # ### end Alembic commands ###
