"""m11 content briefs drafts approvals

Revision ID: 8cc723e57821
Revises: aab4370a01a4
Create Date: 2026-04-12 12:23:38.339612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc723e57821'
down_revision: Union[str, None] = 'aab4370a01a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_briefs',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('campaign_task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('key_message', sa.Text(), nullable=True),
    sa.Column('tone_of_voice', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('reference_urls', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('num_variations', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_task_id'], ['campaign_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_briefs_agency_id'), 'content_briefs', ['agency_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_client_id'), 'content_briefs', ['client_id'], unique=False)
    op.create_table('content_drafts',
    sa.Column('brief_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('variation_number', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('body_copy', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=255), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('angle', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('buffer_post_id', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['brief_id'], ['content_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_drafts_brief_id'), 'content_drafts', ['brief_id'], unique=False)
    op.create_table('client_approval_requests',
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_via', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_channel', sa.String(length=20), nullable=True),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_approval_requests_agency_id'), 'client_approval_requests', ['agency_id'], unique=False)
    op.create_index(op.f('ix_client_approval_requests_client_id'), 'client_approval_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_approval_requests_draft_id'), 'client_approval_requests', ['draft_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_approval_requests_draft_id'), table_name='client_approval_requests')
    op.drop_index(op.f('ix_client_approval_requests_client_id'), table_name='client_approval_requests')
    op.drop_index(op.f('ix_client_approval_requests_agency_id'), table_name='client_approval_requests')
    op.drop_table('client_approval_requests')
    op.drop_index(op.f('ix_content_drafts_brief_id'), table_name='content_drafts')
    op.drop_table('content_drafts')
    op.drop_index(op.f('ix_content_briefs_client_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_agency_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    # ### end Alembic commands ###
