"""m3 reporting

Revision ID: 8e9a9f73d814
Revises: 0c2fb9c9d56c
Create Date: 2026-04-09 23:24:12.108242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9a9f73d814'
down_revision: Union[str, None] = '0c2fb9c9d56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_report_configs',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('schedule', sa.String(length=20), nullable=False),
    sa.Column('platforms', sa.String(length=100), nullable=False),
    sa.Column('ga4_property_id', sa.String(length=100), nullable=True),
    sa.Column('meta_ad_account_id', sa.String(length=100), nullable=True),
    sa.Column('google_ads_customer_id', sa.String(length=100), nullable=True),
    sa.Column('kpi_targets_json', sa.Text(), nullable=True),
    sa.Column('last_report_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_report_configs_agency_id'), 'client_report_configs', ['agency_id'], unique=False)
    op.create_index(op.f('ix_client_report_configs_client_id'), 'client_report_configs', ['client_id'], unique=True)
    op.create_table('reports',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_metrics_json', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_via', sa.String(length=50), nullable=True),
    sa.Column('client_replied', sa.Boolean(), nullable=False),
    sa.Column('follow_up_sent', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_agency_id'), 'reports', ['agency_id'], unique=False)
    op.create_index(op.f('ix_reports_client_id'), 'reports', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_client_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_agency_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_client_report_configs_client_id'), table_name='client_report_configs')
    op.drop_index(op.f('ix_client_report_configs_agency_id'), table_name='client_report_configs')
    op.drop_table('client_report_configs')
    # ### end Alembic commands ###
