"""m6 research competitors briefs

Revision ID: a382f66354a9
Revises: a51cc7959383
Create Date: 2026-04-10 05:28:13.901169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a382f66354a9'
down_revision: Union[str, None] = 'a51cc7959383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_competitors',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('meta_page_id', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_competitors_agency_id'), 'tracked_competitors', ['agency_id'], unique=False)
    op.create_index(op.f('ix_tracked_competitors_client_id'), 'tracked_competitors', ['client_id'], unique=False)
    op.create_table('research_briefs',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('meta_ads_data_json', sa.Text(), nullable=True),
    sa.Column('serp_data_json', sa.Text(), nullable=True),
    sa.Column('brief_text', sa.Text(), nullable=True),
    sa.Column('key_findings_json', sa.Text(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=True),
    sa.Column('acted_on', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['tracked_competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_briefs_agency_id'), 'research_briefs', ['agency_id'], unique=False)
    op.create_index(op.f('ix_research_briefs_client_id'), 'research_briefs', ['client_id'], unique=False)
    op.create_index(op.f('ix_research_briefs_competitor_id'), 'research_briefs', ['competitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_briefs_competitor_id'), table_name='research_briefs')
    op.drop_index(op.f('ix_research_briefs_client_id'), table_name='research_briefs')
    op.drop_index(op.f('ix_research_briefs_agency_id'), table_name='research_briefs')
    op.drop_table('research_briefs')
    op.drop_index(op.f('ix_tracked_competitors_client_id'), table_name='tracked_competitors')
    op.drop_index(op.f('ix_tracked_competitors_agency_id'), table_name='tracked_competitors')
    op.drop_table('tracked_competitors')
    # ### end Alembic commands ###
