"""m5 campaigns campaign tasks

Revision ID: a51cc7959383
Revises: d55f998a3565
Create Date: 2026-04-10 05:17:39.229698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51cc7959383'
down_revision: Union[str, None] = 'd55f998a3565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_agency_id'), 'campaigns', ['agency_id'], unique=False)
    op.create_index(op.f('ix_campaigns_client_id'), 'campaigns', ['client_id'], unique=False)
    op.create_table('campaign_tasks',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buffer_post_id', sa.String(length=255), nullable=True),
    sa.Column('went_live_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_tasks_agency_id'), 'campaign_tasks', ['agency_id'], unique=False)
    op.create_index(op.f('ix_campaign_tasks_assigned_to'), 'campaign_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_campaign_tasks_campaign_id'), 'campaign_tasks', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_tasks_status'), 'campaign_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_tasks_status'), table_name='campaign_tasks')
    op.drop_index(op.f('ix_campaign_tasks_campaign_id'), table_name='campaign_tasks')
    op.drop_index(op.f('ix_campaign_tasks_assigned_to'), table_name='campaign_tasks')
    op.drop_index(op.f('ix_campaign_tasks_agency_id'), table_name='campaign_tasks')
    op.drop_table('campaign_tasks')
    op.drop_index(op.f('ix_campaigns_client_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_agency_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
