"""m10 optimisation configs runs recommendations alerts

Revision ID: aab4370a01a4
Revises: 36454ded30ce
Create Date: 2026-04-10 16:56:25.577818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab4370a01a4'
down_revision: Union[str, None] = '36454ded30ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimisation_configs',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('max_budget_change_pct', sa.Float(), nullable=False),
    sa.Column('max_bid_change_pct', sa.Float(), nullable=False),
    sa.Column('min_daily_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('autonomous_enabled', sa.Boolean(), nullable=False),
    sa.Column('approved_change_types_json', sa.Text(), nullable=False),
    sa.Column('target_roas', sa.Float(), nullable=True),
    sa.Column('target_ctr', sa.Float(), nullable=True),
    sa.Column('target_cpc', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimisation_configs_agency_id'), 'optimisation_configs', ['agency_id'], unique=False)
    op.create_index(op.f('ix_optimisation_configs_client_id'), 'optimisation_configs', ['client_id'], unique=True)
    op.create_table('optimisation_runs',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('performance_snapshot_json', sa.Text(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('total_recommendations', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('executed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimisation_runs_agency_id'), 'optimisation_runs', ['agency_id'], unique=False)
    op.create_index(op.f('ix_optimisation_runs_client_id'), 'optimisation_runs', ['client_id'], unique=False)
    op.create_table('predictive_alerts',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kpi_name', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('projected_eom_value', sa.Float(), nullable=True),
    sa.Column('gap_percentage', sa.Float(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictive_alerts_agency_id'), 'predictive_alerts', ['agency_id'], unique=False)
    op.create_index(op.f('ix_predictive_alerts_client_id'), 'predictive_alerts', ['client_id'], unique=False)
    op.create_table('optimisation_recommendations',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('entity_name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_value', sa.String(length=100), nullable=True),
    sa.Column('proposed_value', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_result', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['optimisation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimisation_recommendations_run_id'), 'optimisation_recommendations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimisation_recommendations_run_id'), table_name='optimisation_recommendations')
    op.drop_table('optimisation_recommendations')
    op.drop_index(op.f('ix_predictive_alerts_client_id'), table_name='predictive_alerts')
    op.drop_index(op.f('ix_predictive_alerts_agency_id'), table_name='predictive_alerts')
    op.drop_table('predictive_alerts')
    op.drop_index(op.f('ix_optimisation_runs_client_id'), table_name='optimisation_runs')
    op.drop_index(op.f('ix_optimisation_runs_agency_id'), table_name='optimisation_runs')
    op.drop_table('optimisation_runs')
    op.drop_index(op.f('ix_optimisation_configs_client_id'), table_name='optimisation_configs')
    op.drop_index(op.f('ix_optimisation_configs_agency_id'), table_name='optimisation_configs')
    op.drop_table('optimisation_configs')
    # ### end Alembic commands ###
