"""m1 communication logs

Revision ID: ac405ac78350
Revises: b67596c2cf25
Create Date: 2026-04-09 04:26:14.894645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac405ac78350'
down_revision: Union[str, None] = 'b67596c2cf25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_logs',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('wati_message_id', sa.String(length=255), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('flag_reviewed', sa.Boolean(), nullable=False),
    sa.Column('flag_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_reviewed_by', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flag_reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_agency_id'), 'communication_logs', ['agency_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_client_id'), 'communication_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_employee_id'), 'communication_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_gmail_message_id'), 'communication_logs', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_communication_logs_is_flagged'), 'communication_logs', ['is_flagged'], unique=False)
    op.create_index(op.f('ix_communication_logs_wati_message_id'), 'communication_logs', ['wati_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_logs_wati_message_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_is_flagged'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_gmail_message_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_employee_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_client_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_agency_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    # ### end Alembic commands ###
