"""m4 churn alerts

Revision ID: d55f998a3565
Revises: 8e9a9f73d814
Create Date: 2026-04-10 05:12:34.399249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55f998a3565'
down_revision: Union[str, None] = '8e9a9f73d814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churn_alerts',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('trigger_reasons_json', sa.Text(), nullable=False),
    sa.Column('retention_actions_json', sa.Text(), nullable=False),
    sa.Column('competitor_context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_churn_alerts_agency_id'), 'churn_alerts', ['agency_id'], unique=False)
    op.create_index(op.f('ix_churn_alerts_client_id'), 'churn_alerts', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_churn_alerts_client_id'), table_name='churn_alerts')
    op.drop_index(op.f('ix_churn_alerts_agency_id'), table_name='churn_alerts')
    op.drop_table('churn_alerts')
    # ### end Alembic commands ###
