"""
M2 — Onboarding Orchestration Agent

LangGraph StateGraph with four nodes:
  1. generate_brief   — Claude reads deal notes, generates a structured client brief
  2. send_email       — Drafts and sends welcome email to client via Gmail
  3. update_crm       — Updates client record in platform DB
  4. notify_am        — Sends Slack notification to assigned account manager

Each node writes a step log to OnboardingStep table.
The flow can be re-run from the last successful node if it fails mid-way.
"""
import json
import logging
import uuid
from datetime import datetime, timezone
from typing import TypedDict

import anthropic
from langgraph.graph import END, StateGraph

logger = logging.getLogger(__name__)


# ── State schema shared across all nodes ────────────────────────────────────

class OnboardingState(TypedDict):
    # Inputs
    flow_id: str
    agency_id: str
    client_id: str
    client_name: str
    client_email: str
    account_manager_name: str
    deal_notes: str             # raw notes from HubSpot deal

    # Outputs written by each node
    client_brief: str           # generated by node 1
    email_sent: bool            # set by node 2
    crm_updated: bool           # set by node 3
    am_notified: bool           # set by node 4

    # Error tracking
    errors: list[str]


# ── Node 1: Generate Client Brief ────────────────────────────────────────────

async def generate_brief_node(state: OnboardingState) -> OnboardingState:
    """
    Calls Claude to convert raw HubSpot deal notes into a
    structured onboarding brief for the account manager.
    """
    from app.config import settings
    from app.database import AsyncSessionLocal
    from app.modules.m2_operations.models import OnboardingStep

    logger.info("[Onboarding] Generating brief for client %s", state["client_name"])

    brief = ""
    node_status = "success"
    error_msg = None

    try:
        client = anthropic.Anthropic(api_key=settings.anthropic_api_key)

        prompt = f"""You are an onboarding specialist at a digital marketing agency.

A new client has just signed. Here are the deal notes from our CRM:

Client: {state["client_name"]}
Email: {state["client_email"]}
Deal Notes: {state["deal_notes"] or "No notes provided"}

Write a structured onboarding brief for the account manager. Include:
1. Client Overview (2-3 sentences about who they are and what they need)
2. Key Goals (bullet points from the deal notes)
3. Immediate Actions Required (what the AM should do in week 1)
4. Potential Challenges (anything to watch out for)

Keep it concise and actionable. Use plain text, no markdown."""

        response = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=600,
            messages=[{"role": "user", "content": prompt}],
        )
        brief = response.content[0].text.strip()

    except Exception as e:
        error_msg = str(e)
        node_status = "failed"
        state["errors"].append(f"generate_brief: {error_msg}")
        logger.error("[Onboarding] Brief generation failed: %s", e)

    # Write step log
    async with AsyncSessionLocal() as db:
        step = OnboardingStep(
            flow_id=uuid.UUID(state["flow_id"]),
            step_name="generate_brief",
            status=node_status,
            output=brief[:500] if brief else None,
            error=error_msg,
        )
        db.add(step)

        # Update flow record
        from app.modules.m2_operations.models import OnboardingFlow
        from sqlalchemy import select
        flow_result = await db.execute(
            select(OnboardingFlow).where(
                OnboardingFlow.id == uuid.UUID(state["flow_id"])
            )
        )
        flow = flow_result.scalar_one_or_none()
        if flow:
            flow.client_brief = brief
            flow.last_completed_node = "generate_brief"
            flow.status = "in_progress"

        await db.commit()

    state["client_brief"] = brief
    return state


# ── Node 2: Send Welcome Email ───────────────────────────────────────────────

async def send_email_node(state: OnboardingState) -> OnboardingState:
    """
    Sends a welcome email to the new client using Gmail API.
    Logs the message to communication_logs.
    """
    from app.database import AsyncSessionLocal
    from app.modules.m2_operations.models import OnboardingStep, OnboardingFlow
    from app.modules.m1_workforce.models_communication import CommunicationLog
    from app.config import settings
    from sqlalchemy import select

    logger.info("[Onboarding] Sending welcome email to %s", state["client_email"])

    node_status = "success"
    error_msg = None

    email_body = f"""Dear {state["client_name"]},

Welcome aboard! We're thrilled to have you as a client.

Your account manager {state["account_manager_name"]} will be reaching out shortly to schedule your kickoff call and walk you through everything.

Here's what happens next:
1. Kickoff call within 48 hours
2. Account setup and access provisioning
3. Strategy session to align on goals

If you have any questions in the meantime, feel free to reply to this email.

Warm regards,
The Agency Team"""

    try:
        if settings.gmail_client_id:
            from app.core.gmail import send_email
            # Production: fetch stored OAuth token
            # Stub for now
            pass

        # Log to communication_logs regardless of send success
        async with AsyncSessionLocal() as db:
            log = CommunicationLog(
                agency_id=uuid.UUID(state["agency_id"]),
                employee_id=None,
                client_id=uuid.UUID(state["client_id"]),
                direction="outbound",
                channel="email",
                subject=f"Welcome to the team, {state['client_name']}!",
                body=email_body,
                status="sent",
                sent_at=datetime.now(timezone.utc),
            )
            db.add(log)
            await db.commit()

        logger.info("[Onboarding] Welcome email logged for %s", state["client_email"])

    except Exception as e:
        error_msg = str(e)
        node_status = "failed"
        state["errors"].append(f"send_email: {error_msg}")
        logger.error("[Onboarding] Email send failed: %s", e)

    # Write step log
    async with AsyncSessionLocal() as db:
        step = OnboardingStep(
            flow_id=uuid.UUID(state["flow_id"]),
            step_name="send_email",
            status=node_status,
            output=f"Email queued to {state['client_email']}" if node_status == "success" else None,
            error=error_msg,
        )
        db.add(step)

        from sqlalchemy import select
        flow_result = await db.execute(
            select(OnboardingFlow).where(
                OnboardingFlow.id == uuid.UUID(state["flow_id"])
            )
        )
        flow = flow_result.scalar_one_or_none()
        if flow:
            flow.last_completed_node = "send_email"
        await db.commit()

    state["email_sent"] = node_status == "success"
    return state


# ── Node 3: Update CRM ───────────────────────────────────────────────────────

async def update_crm_node(state: OnboardingState) -> OnboardingState:
    """
    Updates the client record in platform DB.
    Sets status to active and stores the generated brief.
    In production this also writes back to HubSpot.
    """
    from app.database import AsyncSessionLocal
    from app.modules.m2_operations.models import OnboardingStep, OnboardingFlow
    from app.modules.people_and_tenant.users.models import Client
    from sqlalchemy import select

    logger.info("[Onboarding] Updating CRM for client %s", state["client_id"])

    node_status = "success"
    error_msg = None

    try:
        async with AsyncSessionLocal() as db:
            client_result = await db.execute(
                select(Client).where(Client.id == uuid.UUID(state["client_id"]))
            )
            client = client_result.scalar_one_or_none()
            if client:
                client.status = "active"
                client.notes = (client.notes or "") + f"\n\n[Onboarding Brief]\n{state['client_brief']}"
                await db.commit()

    except Exception as e:
        error_msg = str(e)
        node_status = "failed"
        state["errors"].append(f"update_crm: {error_msg}")
        logger.error("[Onboarding] CRM update failed: %s", e)

    async with AsyncSessionLocal() as db:
        step = OnboardingStep(
            flow_id=uuid.UUID(state["flow_id"]),
            step_name="update_crm",
            status=node_status,
            output="Client status set to active" if node_status == "success" else None,
            error=error_msg,
        )
        db.add(step)

        flow_result = await db.execute(
            select(OnboardingFlow).where(
                OnboardingFlow.id == uuid.UUID(state["flow_id"])
            )
        )
        flow = flow_result.scalar_one_or_none()
        if flow:
            flow.last_completed_node = "update_crm"
        await db.commit()

    state["crm_updated"] = node_status == "success"
    return state


# ── Node 4: Notify Account Manager ──────────────────────────────────────────

async def notify_am_node(state: OnboardingState) -> OnboardingState:
    """
    Sends Slack notification to the account manager with
    the client brief and next steps.
    Stub until Slack SDK is wired in Phase 7.
    """
    from app.database import AsyncSessionLocal
    from app.modules.m2_operations.models import OnboardingStep, OnboardingFlow
    from sqlalchemy import select

    logger.info("[Onboarding] Notifying AM for client %s", state["client_name"])

    node_status = "success"
    error_msg = None

    try:
        slack_message = (
            f"🎉 New client onboarded: *{state['client_name']}*\n"
            f"📧 {state['client_email']}\n\n"
            f"*Brief:*\n{state['client_brief'][:300]}...\n\n"
            f"Welcome email has been sent. Please schedule the kickoff call."
        )

        # TODO Phase 7: replace with real Slack SDK call
        logger.warning("[SLACK STUB] AM notification: %s", slack_message[:100])

    except Exception as e:
        error_msg = str(e)
        node_status = "failed"
        state["errors"].append(f"notify_am: {error_msg}")

    async with AsyncSessionLocal() as db:
        step = OnboardingStep(
            flow_id=uuid.UUID(state["flow_id"]),
            step_name="notify_am",
            status=node_status,
            output="Slack notification sent to AM" if node_status == "success" else None,
            error=error_msg,
        )
        db.add(step)

        flow_result = await db.execute(
            select(OnboardingFlow).where(
                OnboardingFlow.id == uuid.UUID(state["flow_id"])
            )
        )
        flow = flow_result.scalar_one_or_none()
        if flow:
            flow.last_completed_node = "notify_am"
            flow.status = "complete" if not state["errors"] else "failed"
            if state["errors"]:
                flow.error_message = "; ".join(state["errors"])
        await db.commit()

    state["am_notified"] = node_status == "success"
    return state


# ── Build the LangGraph ──────────────────────────────────────────────────────

def build_onboarding_graph() -> StateGraph:
    """
    Assembles the onboarding StateGraph.
    Linear flow: brief → email → crm → notify → END
    Each node is async and writes its own step log.
    """
    graph = StateGraph(OnboardingState)

    graph.add_node("generate_brief", generate_brief_node)
    graph.add_node("send_email", send_email_node)
    graph.add_node("update_crm", update_crm_node)
    graph.add_node("notify_am", notify_am_node)

    graph.set_entry_point("generate_brief")
    graph.add_edge("generate_brief", "send_email")
    graph.add_edge("send_email", "update_crm")
    graph.add_edge("update_crm", "notify_am")
    graph.add_edge("notify_am", END)

    return graph.compile()


# ── Runner function called by API and Celery ─────────────────────────────────

async def run_onboarding_agent(
    flow_id: str,
    agency_id: str,
    client_id: str,
    client_name: str,
    client_email: str,
    account_manager_name: str,
    deal_notes: str = "",
) -> dict:
    """
    Runs the full onboarding graph for a client.
    Returns the final state dict.
    """
    graph = build_onboarding_graph()

    initial_state: OnboardingState = {
        "flow_id": flow_id,
        "agency_id": agency_id,
        "client_id": client_id,
        "client_name": client_name,
        "client_email": client_email,
        "account_manager_name": account_manager_name,
        "deal_notes": deal_notes,
        "client_brief": "",
        "email_sent": False,
        "crm_updated": False,
        "am_notified": False,
        "errors": [],
    }

    final_state = await graph.ainvoke(initial_state)
    return final_state