import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean, DateTime, ForeignKey,
    Integer, Numeric, String, Text
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin


class OnboardingFlow(Base, UUIDMixin, TimestampMixin):
    """
    Tracks the onboarding process for a single client.
    Created when a HubSpot deal closes (webhook) or owner triggers manually.

    status: pending → in_progress → complete | failed
    Each step is logged to OnboardingStep rows.
    """

    __tablename__ = "onboarding_flows"

    agency_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agencies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    client_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # pending | in_progress | complete | failed
    status: Mapped[str] = mapped_column(String(20), default="pending")

    # The AI-generated client brief (output of first LangGraph node)
    client_brief: Mapped[str | None] = mapped_column(Text)

    # HubSpot deal that triggered this (if webhook-initiated)
    hubspot_deal_id: Mapped[str | None] = mapped_column(String(100))

    # Which LangGraph node last ran (for resumability)
    last_completed_node: Mapped[str | None] = mapped_column(String(100))

    error_message: Mapped[str | None] = mapped_column(Text)

    # relationships
    steps: Mapped[list["OnboardingStep"]] = relationship(
        back_populates="flow",
        cascade="all, delete-orphan",
        order_by="OnboardingStep.created_at",
    )

    def __repr__(self) -> str:
        return f"<OnboardingFlow client={self.client_id} status={self.status}>"


class OnboardingStep(Base, UUIDMixin, TimestampMixin):
    """
    Individual step log within an OnboardingFlow.
    Written by each LangGraph node as it completes.
    """

    __tablename__ = "onboarding_steps"

    flow_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("onboarding_flows.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # e.g. "generate_brief" | "send_email" | "update_crm" | "notify_am"
    step_name: Mapped[str] = mapped_column(String(100), nullable=False)

    # success | failed | skipped
    status: Mapped[str] = mapped_column(String(20), default="success")

    # What the step did / returned
    output: Mapped[str | None] = mapped_column(Text)
    error: Mapped[str | None] = mapped_column(Text)

    flow: Mapped["OnboardingFlow"] = relationship(back_populates="steps")

    def __repr__(self) -> str:
        return f"<OnboardingStep {self.step_name} [{self.status}]>"


class Invoice(Base, UUIDMixin, TimestampMixin):
    """
    Invoice issued by agency to a client.
    PDF generated by WeasyPrint on creation.

    status: draft | sent | paid | overdue
    """

    __tablename__ = "invoices"

    agency_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agencies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    client_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    invoice_number: Mapped[str] = mapped_column(
        String(50), nullable=False, unique=True
    )

    # draft | sent | paid | overdue
    status: Mapped[str] = mapped_column(String(20), default="draft")

    # Line items stored as JSON text
    # Format: [{"description": "...", "quantity": 1, "unit_price": 5000.00}]
    line_items_json: Mapped[str] = mapped_column(Text, default="[]")

    subtotal: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))
    tax_percent: Mapped[Decimal] = mapped_column(Numeric(5, 2), default=Decimal("18"))
    tax_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))
    total_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0"))

    due_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    paid_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    notes: Mapped[str | None] = mapped_column(Text)
    pdf_path: Mapped[str | None] = mapped_column(String(500))

    def __repr__(self) -> str:
        return f"<Invoice {self.invoice_number} {self.status} ₹{self.total_amount}>"