import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin


class OutreachSequence(Base, UUIDMixin, TimestampMixin):
    """
    A multi-step outreach campaign for a single lead.
    Generated by Claude using M6 research + M7 lead data as context.

    status: active | paused | completed | replied
    """

    __tablename__ = "outreach_sequences"

    agency_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agencies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    lead_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("leads.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # The employee running this outreach
    assigned_to: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("employees.id", ondelete="SET NULL"),
        nullable=True,
    )

    # active | paused | completed | replied
    status: Mapped[str] = mapped_column(String(30), default="active")

    # How many steps were generated
    total_steps: Mapped[int] = mapped_column(Integer, default=0)

    # Which step is currently pending (1-indexed)
    current_step: Mapped[int] = mapped_column(Integer, default=1)

    # auto | manual — auto sends via Gmail API without AE review
    # manual — AE reviews each message before it goes
    send_mode: Mapped[str] = mapped_column(String(20), default="manual")

    # Context used to generate this sequence
    competitor_context_used: Mapped[str | None] = mapped_column(Text)
    icp_score_at_creation: Mapped[float | None] = mapped_column(
        nullable=True
    )

    # Reply tracking
    replied_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    reply_gmail_message_id: Mapped[str | None] = mapped_column(String(255))

    # relationships
    steps: Mapped[list["OutreachStep"]] = relationship(
        back_populates="sequence",
        cascade="all, delete-orphan",
        order_by="OutreachStep.step_number",
    )

    def __repr__(self) -> str:
        return (
            f"<OutreachSequence lead={self.lead_id} "
            f"status={self.status} step={self.current_step}/{self.total_steps}>"
        )


class OutreachStep(Base, UUIDMixin, TimestampMixin):
    """
    A single message in an OutreachSequence.

    channel : email | linkedin
    status  : pending | sent | skipped | failed
    """

    __tablename__ = "outreach_steps"

    sequence_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("outreach_sequences.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    agency_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agencies.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Which step in the sequence (1, 2, 3...)
    step_number: Mapped[int] = mapped_column(Integer, nullable=False)

    # How many days after the previous step to send
    send_after_days: Mapped[int] = mapped_column(Integer, default=0)

    # email | linkedin
    channel: Mapped[str] = mapped_column(String(20), default="email")

    # Email fields
    subject: Mapped[str | None] = mapped_column(String(500))
    body: Mapped[str] = mapped_column(Text, nullable=False)

    # pending | sent | skipped | failed
    status: Mapped[str] = mapped_column(String(20), default="pending")

    # When this step should be sent (calculated from sequence start + send_after_days)
    scheduled_send_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Gmail message ID for reply detection
    gmail_message_id: Mapped[str | None] = mapped_column(String(255))

    # AE approval for manual mode
    approved_by_ae: Mapped[bool] = mapped_column(Boolean, default=False)

    # relationship
    sequence: Mapped["OutreachSequence"] = relationship(back_populates="steps")

    def __repr__(self) -> str:
        return (
            f"<OutreachStep #{self.step_number} {self.channel} "
            f"[{self.status}] seq={self.sequence_id}>"
        )